version: '3.1'

# There's no backend, just its dependencies (database for example)
# for local development only. Unused in deployments.
# So the idea is running backend on developer's local but its rest dependencies - in docker

services:
  db:
    image: postgres:15.5
    ports:
      - '5431:5432'
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
